name: Release (Legacy)

# This workflow is deprecated in favor of release-and-publish.yml
# It will still run if tags are pushed manually
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Package distribution
      run: |
        tar -czf anon-identity-dist.tar.gz dist/ package.json README.md
        zip -r anon-identity-dist.zip dist/ package.json README.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          anon-identity-dist.tar.gz
          anon-identity-dist.zip
        generate_release_notes: true
        draft: false
        prerelease: false